default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: mobi_comments_development

test:
  <<: *default
  database: mobi_comments_test

production:
  <<: *default
  database: mobi_comments_production
  username: root
  password:
